Update version information

diff --git a/batch/make/version b/batch/make/version
--- a/batch/make/version
+++ b/batch/make/version
@@ -131,74 +131,71 @@ bzr_count_revisions()
 
 # *TODO* once we get our superproject up on launchpad (and thus get saner branch nicks), use branch nicks for $major_version
 # Check if bzr is installed, and if the path is versionned
-bzr >/dev/null 2>&1
+git >/dev/null 2>&1
 # But for now, ignore it
-if test $? -eq 0 && test -d ${srcdir}/.bzr
+if test $? -eq 0 && test -d ${srcdir}/.git
 #if test 1 -eq 0
 then
-    # Crappily, we can't rely on revision numbers to do anything
-    # ( ie. when one merges then pushes, the last revno might be lower than originally)
-    # So we count revisions, including merged ones, also including fools which have empty
-    # lines with only "revno: 15" in their commit messages
-    revno=$( bzr revno ${srcdir} 2>/dev/null)    
-    revcount=$( bzr_count_revisions ${srcdir} )
+    revno=$( git rev-list --count HEAD 2>/dev/null)    
+    revcount=$revno
     lca=$revno
     lcaz=$revcount
     versioned=#
-    branchurl=$( bzr info ${srcdir} 2>/dev/null | sed -ne 's/^  parent branch: \(.*\)$/\1/p' )
+    gitbranch=$(git config --get remote.origin.url 2>/dev/null)
+    branchurl=$(echo ${gitbranch/git@github.com\:/"https://github.com/"}|sed 's/\.[^.]*$//')
 
 
-    # We will check this branch diverged, and/or if tree changed
-    bzrmissingcout=$( cd ${srcdir} && bzr missing --this 2>/dev/null )
-    missing=$?
-    bzr diff ${srcdir} --quiet >/dev/null 2>&1
-    changed=$?
+#     # We will check this branch diverged, and/or if tree changed
+#     bzrmissingcout=$( cd ${srcdir} && bzr missing --this 2>/dev/null )
+#     missing=$?
+#     bzr diff ${srcdir} --quiet >/dev/null 2>&1
+#     changed=$?
         
 
-    if test ${missing} -eq 1
-    # if it diverged:
-    then
-        # Count the revisions we added locally
-        localrevisions=$( echo "${bzrmissingcout}" | sed -ne '2,1s/[^0-9]//gp' )
-        # See how many steps it is, with the fool's number
-        stepsbackwards=$( bzr_count_revisions ${srcdir} ${localrevisions} )
-        # And start dancing.
-        minor_version=_alpha_z$(( ${revcount} - ${stepsbackwards} ))_${DATE}
-        # Set last common ancestors
-        lca=$(( ${revno} - ${localrevisions}))
-        lcaz=$(( ${revcount} - ${stepsbackwards} ))
-        srcchanged=#
-    elif test ${missing} -eq 0 && ( test ${changed} -eq 1 || test ${changed} -eq 2 )
-    then
-        # If a change was made and no more revision was added, just use revision fool's number plus build date
-        minor_version=_alpha_z${revcount}_${DATE}
-        # And this is versionned too
-        srcchanged=#
-    elif test ${missing} -eq 0
-    then
-        # If really no change was made, use the fool's number, with tag if any
-        # So check if we have tags
-        revno=$(bzr revno ${srcdir})
-        tag=$(bzr tags -r $revno | awk '{ print $1 }')
-        if test ${tag}
-        then
-            # If it is tagged, use the tag
-            minor_version=_alpha_z${revcount}_${tag}
-        else
-            # If not, use fool's number only
-            minor_version=_alpha_z${revcount}
-        fi
-        # That's versioned as well
-    else
-        # Otherwise, this is just not versionned
-        versioned=
-    fi
-
-    if test $versioned
-    then
-        branchnick=$( cd ${srcdir}; bzr nick )
-        revid=$( bzr testament | sed -ne 's/^revision-id: \(.*\)/\1/p' )
-    fi
+#     if test ${missing} -eq 1
+#     # if it diverged:
+#     then
+#         # Count the revisions we added locally
+#         localrevisions=$( echo "${bzrmissingcout}" | sed -ne '2,1s/[^0-9]//gp' )
+#         # See how many steps it is, with the fool's number
+#         stepsbackwards=$( bzr_count_revisions ${srcdir} ${localrevisions} )
+#         # And start dancing.
+#         minor_version=_alpha_z$(( ${revcount} - ${stepsbackwards} ))_${DATE}
+#         # Set last common ancestors
+#         lca=$(( ${revno} - ${localrevisions}))
+#         lcaz=$(( ${revcount} - ${stepsbackwards} ))
+#         srcchanged=#
+#     elif test ${missing} -eq 0 && ( test ${changed} -eq 1 || test ${changed} -eq 2 )
+#     then
+#         # If a change was made and no more revision was added, just use revision fool's number plus build date
+#         minor_version=_alpha_z${revcount}_${DATE}
+#         # And this is versionned too
+#         srcchanged=#
+#     elif test ${missing} -eq 0
+#     then
+#         # If really no change was made, use the fool's number, with tag if any
+#         # So check if we have tags
+#         revno=$(bzr revno ${srcdir})
+#         tag=$(bzr tags -r $revno | awk '{ print $1 }')
+#         if test ${tag}
+#         then
+#             # If it is tagged, use the tag
+#             minor_version=_alpha_z${revcount}_${tag}
+#         else
+#             # If not, use fool's number only
+#             minor_version=_alpha_z${revcount}
+#         fi
+#         # That's versioned as well
+#     else
+#         # Otherwise, this is just not versionned
+#         versioned=
+#     fi
+# 
+#     if test $versioned
+#     then
+#         branchnick=$( cd ${srcdir}; bzr nick )
+#         revid=$( bzr testament | sed -ne 's/^revision-id: \(.*\)/\1/p' )
+#     fi
 fi
 
 if test -z "$minor_version"
